### ISSUE TITLE
Why is the right side always empty？

### ISSUE THREAD

**Issue by JackieDing** [opendiffy/diffy#36] opened 2019-12-01 23:46 UTC
![image](https://user-images.githubusercontent.com/15721811/69922512-d9a1b880-14d7-11ea-8aa5-71c05744320e.png)

**Comment by pratyushbansal** [comment] 2019-12-10 19:37
@JackieDing were you able to find any solution to it?

**Comment by alexraknesnav** [comment] 2019-12-19 11:25
This seems to be the same issue as this: https://github.com/twitter/diffy/issues/100

I'm having the same problem, but it only applies to *some* responses. I have yet to figure out what exactly is triggering this bug.

I've probed the API a bit and I've found the following inconsistencies:

URL (1): http://localhost:8888/api/1/endpoints

```
{"localhost-saker":{"total":2,"differences":2}}
```

URL (2): http://localhost:8888/api/1/endpoints/localhost-saker/fields/result/results

```
{"endpoint":"localhost-saker","path":"result","requests":[]}
```

From the first response (1) it seems clear that Diffy have made some comparisons. This can also be seen from the GUI since it shows "100% failing" and the structure of the response. It's also clear from the logs of the upstream apps that they've both been called. However, the second response (2) gives an empty list for `requests` which seems consistent with the screenshot in this issue.

The logfile `differences.log` is empty.
When I try to enable more logging by going to the following address: http://localhost:8881/admin/logging I get the following error message:

> You have not configured a logging handler implementation for TwitterServer.
> Please add a dependency on one of: twitter-server-logback-classic, twitter-server-slf4j-jdk14, or twitter-server-slf4j-log4j12.

**Comment by pratyushbansal** [comment] 2019-12-27 19:38
I observed a unique thing, 
For 200 response's there is nothing displayed on the right side, however for 400 and 404, I get the complete right side screen with all features.
Hoping someone can come-up with solution to this problem

**Comment by pratyushbansal** [comment] 2019-12-27 19:39
@puneetkhanduri

**Comment by pratyushbansal** [comment] 2020-01-01 10:55
Another observation, this issue doesn't exists in the old release ie https://github.com/twitter/diffy/releases/tag/v0.0.1

**Comment by alexraknesnav** [comment] 2020-01-03 11:24
@pratyushbansal I'm unable to build that old release. Docker build complains about certificate path when downloading SBT.

Simply running `./sbt assembly` fails with:
~~~
downloading sbt-launch.jar
OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
~~~

If I remove the offending flags from the `./sbt`-file then I get the following errors:

~~~
diffy-0.0.1$ ./sbt assembly
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/x/.sbt/boot/scala-2.10.5/lib/scala-library.jar(scala/package.class)
error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/x/.sbt/boot/scala-2.10.5/lib/scala-library.jar(scala/runtime/package.class)
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
~~~

I tried various modifications to `build.sbt`, but I just run into a deep hole of various errors. I guess this is not a straight forward workaround...?

**Comment by alexraknesnav** [comment] 2020-01-03 11:55
This bug is a real showstopper. I wish some maintainers will find the time to take a look at it.

**Comment by alexraknesnav** [comment] 2020-01-03 14:06
I investigated it further and it seems that this bug is triggered by `null`-values in the response.

For example, if primary, secondary and candidate all return `{"hello": "world"}` then Diffy works as expected. However, if the candidate returns `{"hello": null}` then that will trigger the bug in this issue. Diffy will show "TypeDifference 100% failing" for value "hello" as expected, but it will be impossible to compare the results as seen in the screenshot by OP.

If the candidate only returns `{}` then Diffy will report "MissingField" and be able to compare the responses as expected.

**Comment by pratyushbansal** [comment] 2020-01-03 15:22
> @pratyushbansal I'm unable to build that old release. Docker build complains about certificate path when downloading SBT.
> 
> Simply running `./sbt assembly` fails with:
> 
> ```
> downloading sbt-launch.jar
> OpenJDK 64-Bit Server VM warning: Option AggressiveOpts was deprecated in version 11.0 and will likely be removed in a future release.
> Unrecognized VM option 'UseParNewGC'
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ```
> 
> If I remove the offending flags from the `./sbt`-file then I get the following errors:
> 
> ```
> diffy-0.0.1$ ./sbt assembly
> OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
> error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/x/.sbt/boot/scala-2.10.5/lib/scala-library.jar(scala/package.class)
> error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/x/.sbt/boot/scala-2.10.5/lib/scala-library.jar(scala/runtime/package.class)
> scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
> 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
> ```
> 
> I tried various modifications to `build.sbt`, but I just run into a deep hole of various errors. I guess this is not a straight forward workaround...?

I didn't try docker with the old release. I was directly running that assembly command and it worked for me.
Which version were you trying? I tried with  v0.0.1 

Yes. I think you are correct regarding the issue. That's why it was working for my api's that are giving 404 because there aren't any null values.
Surprisingly this was very handled in the old version, where it highlighted the null values.
I hope someone fixes it soon enough, its a really useful tool

**Comment by alexraknesnav** [comment] 2020-01-06 07:41
> Which version were you trying? I tried with v0.0.1

That's the version that I tried as well.

**Comment by alexraknesnav** [comment] 2020-01-06 10:04
After attaching a debugger i managed to get the following stacktrace from the point where it fails:

~~~
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class ai.diffy.lifter.JsonLifter$JsonNull$ and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: scala.collection.convert.Wrappers$MapWrapper["200"]->scala.collection.convert.Wrappers$MapWrapper["content"]->scala.collection.convert.Wrappers$MapWrapper["value"]->scala.collection.convert.Wrappers$MapWrapper["hello"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:313)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:722)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:643)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1396)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1120)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:993)
	at ai.diffy.lifter.JsonLifter$.encode(JsonLifter.scala:50)
	at ai.diffy.analysis.DifferenceAnalyzer.$anonfun$apply$1(DifferenceCollector.scala:68)
	at ai.diffy.analysis.DifferenceAnalyzer.$anonfun$apply$1$adapted(DifferenceCollector.scala:46)
	at scala.Option.foreach(Option.scala:274)
	at ai.diffy.analysis.DifferenceAnalyzer.apply(DifferenceCollector.scala:46)
	at ai.diffy.proxy.DifferenceProxy$$anon$1.$anonfun$apply$8(DifferenceProxy.scala:97)
	at ai.diffy.proxy.DifferenceProxy$$anon$1.$anonfun$apply$8$adapted(DifferenceProxy.scala:96)
	at com.twitter.util.Return.map(Try.scala:311)
	at com.twitter.util.Future.$anonfun$map$1(Future.scala:1888)
	at com.twitter.util.ConstFuture.transformTry(ConstFuture.scala:43)
	at com.twitter.util.Future.map(Future.scala:1888)
	at ai.diffy.proxy.DifferenceProxy$$anon$1.$anonfun$apply$6(DifferenceProxy.scala:96)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1798)
	at com.twitter.util.Promise$FutureTransformer.liftedTree1$1(Promise.scala:250)
	at com.twitter.util.Promise$FutureTransformer.k(Promise.scala:250)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:225)
	at com.twitter.util.Promise$WaitQueue.com$twitter$util$Promise$WaitQueue$$run(Promise.scala:101)
	at com.twitter.util.Promise$WaitQueue$$anon$1.run(Promise.scala:96)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:167)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:126)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:243)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:78)
	at com.twitter.util.Promise$WaitQueue.runInScheduler(Promise.scala:96)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:797)
	at com.twitter.util.Promise.update(Promise.scala:769)
	at com.twitter.util.Promise.setValue(Promise.scala:745)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelRead(ChannelTransport.scala:169)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:35)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at com.twitter.finagle.netty4.http.handler.HeaderValidatorHandler$.channelRead(HeaderValidatorHandler.scala:51)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:48)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:155)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
~~~

It appears that Diffy maps `null`-values to an object called `JsonLifter.JsonNull` and then tries to serialize that back to Json (DifferenceCollector.scala:68) without specifying a serializer for that object.

I made the following workaround for the issue. I modified JsonLifter.scala and added the following annotation to `JsonNull`:

~~~scala
@JsonSerialize(using = classOf[JsonNullSerializer])
object JsonNull
~~~

And then I added the following class at the bottom of the file:

~~~scala
class JsonNullSerializer(clazz: Class[Any]) extends StdSerializer[Any](clazz) {
  def this() {
    this(null)
  }

  override def serialize(t: Any, jsonGenerator: JsonGenerator, serializerProvider: SerializerProvider): Unit = {
    jsonGenerator.writeNull()
  }
}
~~~

This kinda works. It brings back the comparison view in the GUI and it shows the diff, but the `null`-value is replaced by an empty space in the GUI which I guess is "good enough" for now.

Screenshot of the result:

![image](https://user-images.githubusercontent.com/53822920/71810927-c902d600-3073-11ea-8596-f17899bf2f15.png)

**Comment by pratyushbansal** [comment] 2020-01-06 10:15
Awesome!
Though I don't think this is default handling in Scala, because Java (Jackson) is able to safely serialize/deserialize null values
Have you created a PR for this change? I was using the docker image for deployment currently.
How are proceeding further? Building your own jar and then deploying it?

Thanks a lot for the solution :)

**Comment by alexraknesnav** [comment] 2020-01-06 11:18
I created a PR for this change now.

> How are proceeding further? Building your own jar and then deploying it?

Not sure yet. I'll probably create a Docker image for it unless it's merged upstream in time.

> Thanks a lot for the solution :)

You're welcome :)

**Comment by yufenyan** [comment] 2020-01-13 04:55
I have the same problem,do you solve the probelm?

**Comment by alexraknesnav** [comment] 2020-01-13 12:02
@yufenyan I don't know if the latest Docker image contains the fix because I built my own with a few additional modifications (although *something* got pushed to dockerhub when my PR was merged so I assume that it's there). If the issue triggers on null-values then I would suggest to try and compile the code from the repo and see if it's still present. Otherwise I think it might be another bug that's triggered by something else. Please let me know if you find the cause as I'm likely stumble into the same problem eventually :)

**Comment by yufenyan** [comment] 2020-01-14 12:24
> @yufenyan I don't know if the latest Docker image contains the fix because I built my own with a few additional modifications (although _something_ got pushed to dockerhub when my PR was merged so I assume that it's there). If the issue triggers on null-values then I would suggest to try and compile the code from the repo and see if it's still present. Otherwise I think it might be another bug that's triggered by something else. Please let me know if you find the cause as I'm likely to stumble into the same problem eventually :)

 @alexraknesnav   I think the docker image contains the fix.And I tried the older version and confirms that it is another bug  which the older stable version also contains. And I wondered if you can build the jar  of the fix  version which you handled .Because I failed to build my own jar. And could you release a   jar for  using .Thanks a lot.

**Closed** 2022-04-18 10:15 UTC
